### PR TITLE
Custom Palette Feature and Bug Fixes

### LINKED ISSUE #23: Full View is not Rendered
When the cell size of the grid is very large, there is space left on the right.  The problem could be in the bleed values.

### LINKED ISSUE #34: View Disappears on Rotating Screen
The main view triangulation disappears on rotating the screen from portrait to landscape orientation. This happens when the triangulation has been set by attributes, and then the triangulation is updated without any changes to the triangulation. There is a fault in the `generateAndInvalidate` method.

### LINKED ISSUE #35: Checkbox Anomalies on Regeneration
If both Draw Strokes and Fill Triangles checkboxes are unticked by the regenerator, then there is a mismatch between the checkboxes and the rendered view.

### LINKED ISSUE #36: App Crashes on Fast Regeneration
If the regenerate button is clicked fast and repeatedly, the app crashes.  This is due to 'divide by 0' error when the grid is generated by calling random on the variance of value 0.

### PR DESCRIPTION
**Pull request by dakshitagrawal**
This PR-
* adds the Custom Palette Feature to the demo app. It has a separate button to go to a custom palette picker, which provides the option of selecting the suitable colors and setting it as the custom palette. On the main view, whenever the triangulation is to be colorized with the custom palette, the Custom Palette Checkbox can be ticked.
* fixes #23 
* fixes #34
* fixes #35 
* fixes #36

### CODE REVIEW

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+                R.id.custom_palette_c6, R.id.custom_palette_c7, R.id.custom_palette_c8};
+
+        final ImageView[] imageViews = {c0, c1, c2, c3, c4, c5, c6, c7, c8};
+
+        for (int i = 0; i < imageViews.length; i++) {
+            imageViews[i] = (ImageView) findViewById(imageViewID[i]);
+            imageViews[i].setBackgroundColor(colors[i]);
+            final int finalI = i;
+
+            imageViews[i].setOnClickListener(new View.OnClickListener() {
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+        switch (item.getItemId()) {
+            case android.R.id.home:
+                onBackPressed();
+                return true;
+            case R.id.custom_palette_ok:
+                Intent intent = new Intent();
+                intent.putExtra("Custom Palette Color Array", colors);
+                setResult(RESULT_OK, intent);
+                onBackPressed();
+            default:
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: Fall through from previous branch of the switch statement\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 3]
```diff
@@ -51,11 +56,12 @@ public void onStopTrackingTouch(SeekBar seekBar) {
 
             }
         });
+
         cellSizeSeekBar = (SeekBar) findViewById(R.id.cell_size_seekbar);
         int maxCellSize = 150;
 
         cellSizeSeekBar.setMax(maxCellSize);
-        cellSizeSeekBar.setProgress(trianglifyView.getCellSize());
+        cellSizeSeekBar.setProgress(trianglifyView.getCellSize()-100);
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\-' is not preceded with whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\-' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 4]
```diff
@@ -189,6 +211,12 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 randomizeTrianglifyParameters(trianglifyView);
                 trianglifyView.generateAndInvalidate();
                 break;
+            // action with ID custom_palette_picker was selected
+            case R.id.custom_palette_picker:
+                Intent customPalettePickerIntent = new Intent(this, CustomPalettePickerActivity.class);
+                customPalettePickerIntent.putExtra("Palette Color Array",trianglifyView.getPalette().getColors());
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 5]
```diff
@@ -189,6 +211,12 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                startActivityForResult(customPalettePickerIntent,1);
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 6]
```diff
@@ -197,6 +225,19 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-            Toast.makeText(this, "view should at least be set to draw strokes or fill triangles or both.", Toast.LENGTH_LONG).show();
+        Toast.makeText(this, "view should at least be set to draw strokes or fill triangles or both.", Toast.LENGTH_LONG).show();
+    }
+
+    public void onActivityResult(int requestCode, int resultCode, Intent data) {
+        super.onActivityResult(requestCode, resultCode, data);
+        if (requestCode == 1) {
+            if (resultCode == RESULT_OK) {
+                customPalette = new Palette(data.getIntArrayExtra("Custom Palette Color Array"));
+                if ( customPaletteCheckbox.isChecked()) {
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: Nested if\-else depth is 2 \(max allowed is 1\)\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 1 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 2 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: Fall through from previous branch of the switch statement\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 3 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\-' is not preceded with whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\-' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 7]
```diff
@@ -189,6 +217,12 @@ public boolean onOptionsItemSelected(MenuItem item) {
                 randomizeTrianglifyParameters(trianglifyView);
                 trianglifyView.generateAndInvalidate();
                 break;
+            // action with ID custom_palette_picker was selected
+            case R.id.custom_palette_picker:
+                Intent customPalettePickerIntent = new Intent(this, CustomPalettePickerActivity.class);
+                customPalettePickerIntent.putExtra("Palette Color Array",trianglifyView.getPalette().getColors());
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 8]
```diff
@@ -189,6 +217,12 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
+                startActivityForResult(customPalettePickerIntent,1);
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 9]
```diff
@@ -197,6 +231,19 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-            Toast.makeText(this, "view should at least be set to draw strokes or fill triangles or both.", Toast.LENGTH_LONG).show();
+        Toast.makeText(this, "view should at least be set to draw strokes or fill triangles or both.", Toast.LENGTH_LONG).show();
+    }
+
+    public void onActivityResult(int requestCode, int resultCode, Intent data) {
+        super.onActivityResult(requestCode, resultCode, data);
+        if (requestCode == 1) {
+            if (resultCode == RESULT_OK) {
+                customPalette = new Palette(data.getIntArrayExtra("Custom Palette Color Array"));
+                if ( customPaletteCheckbox.isChecked()) {
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: Nested if\-else depth is 2 \(max allowed is 1\)\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 1 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 2 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: Fall through from previous branch of the switch statement\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 3 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\-' is not preceded with whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\-' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 7 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 8 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 9 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: Nested if\-else depth is 2 \(max allowed is 1\)\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 10]
```diff
@@ -22,6 +22,7 @@
     int typeGrid;
     int variance;
     int cellSize;
+    boolean fillViewCompletely;
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: Variable 'fillViewCompletely' must be private and have accessor methods\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 11]
```diff
@@ -345,4 +365,10 @@ public void drawTriangle(Canvas canvas, Triangle2D triangle2D) {
 
         canvas.drawPath(path, paint);
     }
+
+    public void checkViewFilledCompletely(){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 12]
```diff
@@ -0,0 +1,131 @@
...
+    private Context context;
+    private ImageView c0;
+    private ImageView c1;
+    private ImageView c2;
+    private ImageView c3;
+    private ImageView c4;
+    private ImageView c5;
+    private ImageView c6;
+    private ImageView c7;
+    private ImageView c8;
```
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: Remove individual declaration of ImageViews instead declare an array of ImageView and then intialize corresponding objects using a for loop and something like `item.setThumbnailID(activity.getResources().getIdentifier(imageName, "drawable", activity.getPackageName()));` to get id of ImageView, since alll the imageViews are numbered. 

Code should not contain individual ImageView use just arrays, everu operation can be performed using for loop

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 13]
```diff
@@ -0,0 +1,131 @@
...
+
+        context = this;
+
+        trianglifyView = (TrianglifyView) findViewById(R.id.trianglify_custom_palette_view);
+        trianglifyView.setPalette(new Palette(colors));
+        trianglifyView.smartUpdate();
+
+        int[] imageViewID = {R.id.custom_palette_c0, R.id.custom_palette_c1, R.id.custom_palette_c2,
+                R.id.custom_palette_c3, R.id.custom_palette_c4, R.id.custom_palette_c5,
+                R.id.custom_palette_c6, R.id.custom_palette_c7, R.id.custom_palette_c8};
```
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: use for loop  to initialize these

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 14]
```diff
@@ -0,0 +1,131 @@
...
+    public boolean onOptionsItemSelected(MenuItem item) {
+        switch (item.getItemId()) {
+            case android.R.id.home:
+                onBackPressed();
+                return true;
+            case R.id.custom_palette_ok:
+                Intent intent = new Intent();
+                intent.putExtra("Custom Palette Color Array", colors);
+                setResult(RESULT_OK, intent);
+                onBackPressed();
```
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: Shouldn't there be a break statement?

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 7 above)
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: Use something like [this](http://stackoverflow.com/questions/4433790/naming-convention-for-passing-data-through-extras-in-android) instead of hard coding `"Palette Color Array"`

File: app/src/main/res/drawable/color_picked_imageview_border.xml [hunk 15]
```diff
@@ -0,0 +1,5 @@
+<?xml version="1.0" encoding="utf-8"?>
+<shape xmlns:android="http://schemas.android.com/apk/res/android">
+    <stroke android:width="2dp" android:color="#bdbdbd"/>
+    <padding android:left="1dp" android:top="1dp" android:right="1dp" android:bottom="1dp"/>
+</shape>
```
Comment (suyashmahar) [inline app/src/main/res/drawable/color_picked_imageview_border.xml]: no LF at end of file

File: app/src/main/res/drawable/ok_icon.xml [hunk 16]
```diff
@@ -0,0 +1,8 @@
+<?xml version="1.0" encoding="utf-8"?>
+<vector xmlns:android="http://schemas.android.com/apk/res/android"
+    android:height="48dp"
+    android:width="48dp"
+    android:viewportWidth="24"
+    android:viewportHeight="24">
+    <path android:fillColor="#fff" android:pathData="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" />
+</vector>
```
Comment (suyashmahar) [inline app/src/main/res/drawable/ok_icon.xml]: no LF at end of file

File: app/src/main/res/drawable/palette_icon.xml [hunk 17]
```diff
@@ -0,0 +1,8 @@
+<?xml version="1.0" encoding="utf-8"?>
+<vector xmlns:android="http://schemas.android.com/apk/res/android"
+    android:height="48dp"
+    android:width="48dp"
+    android:viewportWidth="24"
+    android:viewportHeight="24">
+    <path android:fillColor="#efeaeaea" android:pathData="M17.5,12A1.5,1.5 0 0,1 16,10.5A1.5,1.5 0 0,1 17.5,9A1.5,1.5 0 0,1 19,10.5A1.5,1.5 0 0,1 17.5,12M14.5,8A1.5,1.5 0 0,1 13,6.5A1.5,1.5 0 0,1 14.5,5A1.5,1.5 0 0,1 16,6.5A1.5,1.5 0 0,1 14.5,8M9.5,8A1.5,1.5 0 0,1 8,6.5A1.5,1.5 0 0,1 9.5,5A1.5,1.5 0 0,1 11,6.5A1.5,1.5 0 0,1 9.5,8M6.5,12A1.5,1.5 0 0,1 5,10.5A1.5,1.5 0 0,1 6.5,9A1.5,1.5 0 0,1 8,10.5A1.5,1.5 0 0,1 6.5,12M12,3A9,9 0 0,0 3,12A9,9 0 0,0 12,21A1.5,1.5 0 0,0 13.5,19.5C13.5,19.11 13.35,18.76 13.11,18.5C12.88,18.23 12.73,17.88 12.73,17.5A1.5,1.5 0 0,1 14.23,16H16A5,5 0 0,0 21,11C21,6.58 16.97,3 12,3Z" />
+</vector>
```
Comment (suyashmahar) [inline app/src/main/res/drawable/palette_icon.xml]: no LF at end of file

File: app/src/main/res/values/styles.xml [hunk 18]
```diff
@@ -3,8 +3,8 @@
     <!-- Base application theme. -->
     <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
         <!-- Customize your theme here. -->
-        <item name="colorPrimary">@color/colorPrimary</item>
-        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
+        <item name="colorPrimary">#009688</item>
+        <item name="colorPrimaryDark">#00796B</item>
```
Comment (suyashmahar) [inline app/src/main/res/values/styles.xml]: Why are colors hardcoded?

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java [hunk 19]
```diff
@@ -131,11 +131,13 @@ public static Palette getPalette(int paletteIndex) {
      */
     public static int indexOf(Palette palette) {
         int pos = -1;
+
         for (int i = 0; i < Palette.DEFAULT_PALETTE_COUNT; i++) {
-            if (Palette.getPalette(i) == palette) {
+            if ( Palette.getPalette(i).getColors()[8] == palette.getColors()[8] ) {
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java]: ye kyun?

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 20]
```diff
@@ -109,10 +111,22 @@ public int getCellSize() {
     public TrianglifyView setCellSize(int cellSize) {
         this.cellSize = cellSize;
         this.viewState = ViewState.GRID_PARAMETERS_CHANGED;
+        if ( fillViewCompletely ) {
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: pure code base mein `if (` ke baad space nahi eisa karne se code inconsistent ho jayega

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 21]
```diff
@@ -79,6 +80,7 @@ public void attributeSetter(TypedArray typedArray) {
             palette = Palette.getPalette(paletteNumber);
             typeGrid = GRID_RECTANGLE;
             randomColoring = typedArray.getBoolean(R.styleable.TrianglifyView_randomColoring, false);
+            fillViewCompletely = typedArray.getBoolean(R.styleable.TrianglifyView_fillViewCompletely, false);
         }finally {
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: space before finally

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 22]
```diff
@@ -109,10 +111,22 @@ public int getCellSize() {
...
+        }
         return this;
     }
 
     @Override
+    public void setFillViewCompletely(boolean fillViewCompletely) {
+        this.fillViewCompletely = fillViewCompletely;
+    }
+
+    public boolean isFillViewCompletely() {
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Is saab ko document kyun nahi kara?

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java [hunk 23]
```diff
@@ -27,8 +27,11 @@ public ThreadLocalRandom(long seed) {
      * @return Random number between 0 and mod (exclusive)
      */
     public int nextInt(int mod) {
-        seed = (seed * 0x5DEECE66DL + 0xBL) & ((1L << 48) - 1);
-        return (int)(seed%mod);
+        if ( mod != 0 ) {
+            seed = (seed * 0x5DEECE66DL + 0xBL) & ((1L << 48) - 1);
+            return (int) (seed % mod);
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java:32]: (int) ke baad space nahi hona chahiye

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java [hunk 24]
```diff
@@ -64,61 +64,61 @@ public void setColors(int[] colors) {
...
+                return new Palette(0xff67001f, 0xffb2182b, 0xffd6604d, 0xfff4a582, 0xfffddbc7, 0xffffffff, 0xffe0e0e0, 0xffbababa, 0xff878787);
             case RD_YL_BU:
-                return new Palette(0xa50026, 0xd73027, 0xf46d43, 0xfdae61, 0xfee090, 0xffffbf, 0xe0f3f8, 0xabd9e9, 0x74add1);
+                return new Palette(0xffa50026, 0xffd73027, 0xfff46d43, 0xfffdae61, 0xfffee090, 0xffffffbf, 0xffe0f3f8, 0xffabd9e9, 0xff74add1);
             case SPECTRAL:
-                return new Palette(0x9e0142, 0xd53e4f, 0xf46d43, 0xfdae61, 0xfee08b, 0xffffbf, 0xe6f598, 0xabdda4, 0x66c2a5);
+                return new Palette(0xff9e0142, 0xffd53e4f, 0xfff46d43, 0xfffdae61, 0xfffee08b, 0xffffffbf, 0xffe6f598, 0xffabdda4, 0xff66c2a5);
             case RD_YL_GN:
-                return new Palette(0xa50026, 0xd73027, 0xf46d43, 0xfdae61, 0xfee08b, 0xffffbf, 0xd9ef8b, 0xa6d96a, 0x66bd63);
+                return new Palette(0xffa50026, 0xffd73027, 0xfff46d43, 0xfffdae61, 0xfffee08b, 0xffffffbf, 0xffd9ef8b, 0xffa6d96a, 0xff66bd63);
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java]: All logic earlier implemented assumes no alpha channel is present in colors, it would break previous code

File: build.gradle [hunk 25]
```diff
@@ -17,6 +17,7 @@ buildscript {
 allprojects {
     repositories {
         jcenter()
+        maven { url "https://jitpack.io" }
```
Comment (suyashmahar) [inline build.gradle:20]: Why this?

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 9 above)
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: `( custom...` no space should be there

**Review by suyashmahar — CHANGES_REQUESTED** [review]
Always update documentation along with development, catching up with the development would be difficult later.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 12 above)
Comment (dakshitagrawal97) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: done in commit#c77efe3

Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: ok

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 14 above)
Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: yeah, my bad.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java (hunk 24 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java]: I will see if there is another way.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java (hunk 19 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java]: the last color of each palette is different. So less comparison.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 20 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: 👍

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 22 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Once the code is finalized, then I will do it.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java (hunk 23 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java:32]: ok

File: build.gradle (hunk 25 above)
Comment (dakshitagrawal) [reply build.gradle:20]: required for colorpicker

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 7 above)
Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: 👍

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java (hunk 19 above)
Comment (suyashmahar) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java]: Should comment on such code which use different logic than what is obvious, moreover this thing can break if any two color has same last color in future. Also just three of the colors are repeated as first colors in palette, won't make any significant difference in performance. Most of the time is spent on triangulatiion which is >> time spent on coloring

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 22 above)
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: +1

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 1 above)
Comment (dakshitagrawal) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: N/A

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 26]
```diff
@@ -0,0 +1,121 @@
...
+
+        context = this;
+
+        trianglifyView = (TrianglifyView) findViewById(R.id.trianglify_custom_palette_view);
+        trianglifyView.setPalette(new Palette(colors));
+        trianglifyView.smartUpdate();
+
+        for (int i = 0; i < imageViews.length; i++) {
+            String imageViewNumber = "custom_palette_c" + String.valueOf(i);
+            int resID = getResources().getIdentifier(imageViewNumber,"id",getPackageName());
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: ',' is not followed by whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 27]
```diff
@@ -0,0 +1,121 @@
...
+            imageViews[i] = (ImageView) findViewById(resID);
+            imageViews[i].setBackgroundColor(colors[i] + 0xff000000);
+
+            final int finalI = i;
+
+            imageViews[i].setOnClickListener(new View.OnClickListener() {
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java [hunk 28]
```diff
@@ -27,8 +27,11 @@ public ThreadLocalRandom(long seed) {
      * @return Random number between 0 and mod (exclusive)
      */
     public int nextInt(int mod) {
-        seed = (seed * 0x5DEECE66DL + 0xBL) & ((1L << 48) - 1);
-        return (int)(seed%mod);
+        if ( mod != 0 ) {
+            seed = (seed * 0x5DEECE66DL + 0xBL) & ((1L << 48) - 1);
+            return (int)(seed % mod);
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java]: \[Checkstyle\] ERROR: 'typecast' is not followed by whitespace\.

File: app/src/main/res/drawable/color_picked_imageview_border.xml (hunk 15 above)
Comment (dakshitagrawal) [reply app/src/main/res/drawable/color_picked_imageview_border.xml]: done

File: app/src/main/res/drawable/ok_icon.xml (hunk 16 above)
Comment (dakshitagrawal) [reply app/src/main/res/drawable/ok_icon.xml]: done

File: app/src/main/res/drawable/palette_icon.xml (hunk 17 above)
Comment (dakshitagrawal) [reply app/src/main/res/drawable/palette_icon.xml]: done

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java (hunk 24 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java]: not done

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 27 above)
Comment (dakshitagrawal) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:57]: N/A

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java (hunk 28 above)
Comment (dakshitagrawal) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java]: @suyashmahar http://www.oracle.com/technetwork/java/codeconventions-150003.pdf

Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java]: just looked it up 😅

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 26 above)
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: @dakshitagrawal97 ^

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java (hunk 24 above)
Comment (suyashmahar) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/models/Palette.java]: @dakshitagrawal97 Nahi sahi hai alpha channel ho ya na ho phir bhi kaam karega kyun ki 32 bits mein `0xff000000*2 == 0xff000000`

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 29]
```diff
@@ -345,4 +355,10 @@ public void drawTriangle(Canvas canvas, Triangle2D triangle2D) {
 
         canvas.drawPath(path, paint);
     }
+
+    private void checkViewFilledCompletely() {
+        if (bleedY <= cellSize || bleedX <= cellSize) {
+            throw new IllegalArgumentException("bleedY and bleedX should be larger than cellSize for view to be completely filled.");
+        }
+    }
 }
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: No LF

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 30]
```diff
@@ -79,36 +76,37 @@ public void attributeSetter(TypedArray typedArray) {
             palette = Palette.getPalette(paletteNumber);
             typeGrid = GRID_RECTANGLE;
             randomColoring = typedArray.getBoolean(R.styleable.TrianglifyView_randomColoring, false);
-        }finally {
+            fillViewCompletely = typedArray.getBoolean(R.styleable.TrianglifyView_fillViewCompletely, false);
+        } finally {
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Catch this exception

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 31]
```diff
@@ -66,8 +63,8 @@ protected void onSizeChanged(int width, int height, int oldWidth, int oldHeight)
         gridHeight = height;
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Why this? These things make getters and setters meaningless

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 32]
```diff
@@ -0,0 +1,121 @@
...
+    @Override
+    protected void onCreate(Bundle savedInstanceState) {
+        super.onCreate(savedInstanceState);
+        setContentView(R.layout.activity_custom_palette_picker);
+
+        ActionBar actionBar = getSupportActionBar();
+        actionBar.setDisplayHomeAsUpEnabled(true);
+        actionBar.setTitle("Custom Palette Picker");
+
+        colors = getIntent().getIntArrayExtra(MainActivity.PALETTE_COLOR_ARRAY);
```
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: isko strings.xml ya aisi kisi global jagha define kar de, taaki ek jagha sari strings rahe aur collisions na ho

**Review by suyashmahar — CHANGES_REQUESTED** [review]

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 31 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: was there much before this PR. Let me see.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 30 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Again was there much before. I will look into it.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 31 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: I do not understand in which context you are saying. Do you mean the onSizeChanged method is unnecessary, or do you mean that I should call the gridHeight via getters?

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 32 above)
Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: Not possible to define it in a static sense.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 33]
```diff
@@ -0,0 +1,121 @@
...
+
+        for (int i = 0; i < imageViews.length; i++) {
+            String imageViewNumber = "custom_palette_c" + String.valueOf(i);
+            int resID = getResources().getIdentifier(imageViewNumber, "id", getPackageName());
+            imageViews[i] = (ImageView) findViewById(resID);
+            imageViews[i].setBackgroundColor(colors[i] + 0xff000000);
+
+            final int finalI = i;
+
+            imageViews[i].setOnClickListener(new View.OnClickListener() {
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:57]: \[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java [hunk 34]
```diff
@@ -0,0 +1,121 @@
...
+                @Override
+                public void onClick(View v) {
+                    final AlertDialog dialog = ColorPickerDialogBuilder
+                            .with(context)
+                            .initialColor(colors[finalI]+0xff000000)
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: '\+' is not preceded with whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java]: \[Checkstyle\] ERROR: '\+' is not followed by whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java (hunk 23 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java:32]: N/A

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 33 above)
Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:57]: N/A

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:57]: \[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:57]: N/A

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 32 above)
Comment (suyashmahar) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: why not?

Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: public static final PALETTE_COLOR_ARRAY = getResources or getStrings.  Both method cannot be applied in static sense.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java (hunk 23 above)
Comment (suyashmahar) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java:32]: Why

Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/utilities/ThreadLocalRandom.java:32]: java conventions

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 32 above)
Comment (suyashmahar) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: Then why are you storing value form strings.xml to a variable just use it directly in the method (or with a variable with scope limited to that method)

Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: I have not stored any value from strings.xml
i have defined a public static final keyword to be used in intent extras as given in the example at android developers

Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: https://developer.android.com/training/basics/firstapp/starting-activity.html
@suyashmahar

Comment (suyashmahar) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: Oh, sorry I got confused

Comment (suyashmahar) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:41]: But what I was saying is declaring such strings globally in project so that they can be accessed from any class. This will help in managing such strings easily, allows editing content of string without changing them at every place they are used.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java (hunk 33 above)
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:57]: \[Checkstyle\] ERROR: Anonymous inner class length is 39 lines \(max allowed is 20\)\.

Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/CustomPalettePickerActivity.java:57]: N/A
