### PR TITLE
Bug fixes

### LINKED ISSUE #19: [Performance Improvement] Disabling regeneration of Triangulation on change of unrelated parameters
Trianglify currently regenerates triangulation when stroke or filling of triangles is toggled, this waste resources and decreases performance. Instead Triangulation should be regenerated on change of variance, cell size or bleed.

### LINKED ISSUE #22: Anomalies in Draw Strokes and Fill Triangles Checkbox
The view is shown even when the Draw Strokes checkbox, as well as the Fill Triangles checkbox, is unchecked.

### PR DESCRIPTION
**Pull request by dakshitagrawal**
This PR:
Fixes #19
Fixes #22.

### CODE REVIEW

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 1]
```diff
@@ -100,8 +100,14 @@ public void onStopTrackingTouch(SeekBar seekBar) {
         strokeCheckBox.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
             @Override
             public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
-                trianglifyView.setDrawStrokeEnabled(isChecked);
-                trianglifyView.generateAndInvalidate();
+                if(isChecked || trianglifyView.isFillTriangle()){
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 2]
```diff
@@ -100,8 +100,14 @@ public void onStopTrackingTouch(SeekBar seekBar) {
...
+                    trianglifyView.setDrawStrokeEnabled(isChecked);
+                    strokeCheckBox.setChecked(isChecked);
+                    trianglifyView.invalidate();
+                }else{
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: 'else' is not preceded with whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\}' is not followed by whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: 'else' is not followed by whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 3]
```diff
@@ -110,8 +116,14 @@ public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
         fillCheckBox.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
             @Override
             public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
-                trianglifyView.setFillTriangle(isChecked);
-                trianglifyView.generateAndInvalidate();
+                if(isChecked || trianglifyView.isDrawStrokeEnabled()){
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 4]
```diff
@@ -110,8 +116,14 @@ public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
...
+                    trianglifyView.setFillTriangle(isChecked);
+                    fillCheckBox.setChecked(isChecked);
+                    trianglifyView.invalidate();
+                }else{
```
Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: 'else' is not preceded with whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\}' is not followed by whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: 'else' is not followed by whitespace\.

Comment (sputnikci) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java [hunk 5]
```diff
@@ -31,11 +31,20 @@
     private TrianglifyViewInterface view;
     private Triangulation triangulation;
     private TriangleGeneratorTask generatorTask;
+    int justColor = 0;
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: \[Checkstyle\] ERROR: Variable 'justColor' explicitly initialized to '0' \(default value for its type\)\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: \[Checkstyle\] ERROR: Variable 'justColor' must be private and have accessor methods\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java [hunk 6]
```diff
@@ -69,7 +78,11 @@ public Presenter(TrianglifyViewInterface view) {
      * @return triangulation corresponding to current instance parameters
      */
     public Triangulation getSoup() {
-        generateSoup();
+        if(justColor == 0){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java [hunk 7]
```diff
@@ -69,7 +78,11 @@ public Presenter(TrianglifyViewInterface view) {
...
+            generateSoup();
+        }else if(justColor == 1){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: \[Checkstyle\] ERROR: 'else' is not preceded with whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: \[Checkstyle\] ERROR: '\}' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 8]
```diff
@@ -23,6 +24,16 @@
...
 
+    /**
+     * flag for change in attributes
+     * if triangulation is null then value is -2
+     * if triangulation is unchanged then value is -1
+     * if change in grid width, grid height, variance, bleedX, bleedY, typeGrid or cell size then value is 1
+     * if change in palette or random coloring then value is 2
+     * if change in fillTriangle or drawStroke then value is 0
+     */
+    int flagForChangeInRelatedParameters = -2;
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: Variable 'flagForChangeInRelatedParameters' must be private and have accessor methods\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 9]
```diff
@@ -73,16 +84,24 @@ public Palette getPalette() {
 
     public TrianglifyView setPalette(Palette palette) {
         this.palette = palette;
+        if(this.flagForChangeInRelatedParameters != 1){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 10]
```diff
@@ -179,6 +205,9 @@ public boolean isFillTriangle() {
 
     public TrianglifyView setFillTriangle(boolean fillTriangle) {
         this.fillTriangle = fillTriangle;
+        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 11]
```diff
@@ -189,6 +218,9 @@ public boolean isDrawStrokeEnabled() {
 
     public TrianglifyView setDrawStrokeEnabled(boolean drawStroke) {
         this.drawStroke = drawStroke;
+        if(this.flagForChangeInRelatedParameters != 1 && this.flagForChangeInRelatedParameters != 2){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 12]
```diff
@@ -199,6 +231,9 @@ public boolean isRandomColoringEnabled() {
 
     public TrianglifyView setRandomColoring(boolean randomColoring) {
         this.randomColoring = randomColoring;
+        if(this.flagForChangeInRelatedParameters != 1){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 13]
```diff
@@ -207,14 +242,29 @@ protected void onDraw(Canvas canvas) {
         super.onDraw(canvas);
         gridHeight = getHeight();
         gridWidth = getWidth();
-        if (this.triangulation != null) {
+
+        if(flagForChangeInRelatedParameters == 0)  {
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 14]
```diff
@@ -207,14 +242,29 @@ protected void onDraw(Canvas canvas) {
...
+            Log.d("just plotting", "just plot");
             plotOnCanvas(canvas);
-        } else {
+        }else if( flagForChangeInRelatedParameters == -1) {
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'else' is not preceded with whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\}' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 15]
```diff
@@ -207,14 +242,29 @@ protected void onDraw(Canvas canvas) {
...
+            plotOnCanvas(canvas);
+        }
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\}' at column 9 should be on the same line as the next part of a multi\-block statement\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 16]
```diff
@@ -207,14 +242,29 @@ protected void onDraw(Canvas canvas) {
...
+        else if(flagForChangeInRelatedParameters == 2){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 17]
```diff
@@ -6,6 +6,7 @@
 import android.graphics.Paint;
 import android.graphics.Path;
 import android.util.AttributeSet;
+import android.util.Log;
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: Unused import \- android\.util\.Log\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 9 above)
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 10 above)
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 11 above)
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 12 above)
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 18]
```diff
@@ -207,14 +242,23 @@ protected void onDraw(Canvas canvas) {
         super.onDraw(canvas);
         gridHeight = getHeight();
         gridWidth = getWidth();
-        if (this.triangulation != null) {
+
+        if (flagForChangeInRelatedParameters == 0 || flagForChangeInRelatedParameters == -1) {
             plotOnCanvas(canvas);
-        } else {
+        } else if(flagForChangeInRelatedParameters == 2) {
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 19]
```diff
@@ -207,14 +242,23 @@ protected void onDraw(Canvas canvas) {
...
+            generateNewColoredSoupAndInvalidate(canvas);
+        } else if(flagForChangeInRelatedParameters == 1 || flagForChangeInRelatedParameters == -2) {
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: 'if' is not followed by whitespace\.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 20]
```diff
@@ -207,14 +242,23 @@ protected void onDraw(Canvas canvas) {
...
             generateAndInvalidate();
         }
     }
 
+    void generateNewColoredSoupAndInvalidate(Canvas canvas){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: README.md [hunk 21]
```diff
@@ -88,8 +88,7 @@ trianglifyView.setGridWidth(trianglifyView.getWidth())
     app:fillTriangle="true" />
 ```
 
-> TrianglifyView should be invalidated on change of any of the parameter for changes to take effect.To invalidate TrianglifyView call generateAndInvalidate method of TrianglifyView class.  
-**Note:** If any of the parameters is changed `TrianglifyView` regenerates every thing from scratch
+> TrianglifyView should be invalidated on change of any of the parameter for changes to take effect. To invalidate TrianglifyView call invalidate method on the Trianglify View Instance.
```
Comment (suyashmahar) [inline README.md]: method to invalidate view for any changes to take effect is generateAndInvalidate

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 22]
```diff
@@ -207,14 +241,30 @@ protected void onDraw(Canvas canvas) {
...
         gridWidth = getWidth();
-        if (this.triangulation != null) {
+        if (triangulation != null) {
             plotOnCanvas(canvas);
         } else {
             generateAndInvalidate();
         }
     }
 
+    public void updateView(){
```
Comment (sputnikci) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: \[Checkstyle\] ERROR: '\{' is not preceded with whitespace\.

File: README.md (hunk 21 above)
Comment (suyashmahar) [reply README.md]: Add behavioral description of following here or in a new point
* `invalidate`
* `generateAndInvalidate`

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 23]
```diff
@@ -60,7 +60,7 @@ public void onStopTrackingTouch(SeekBar seekBar) {
             @Override
             public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                 trianglifyView.setCellSize(progress+100);
-                trianglifyView.generateAndInvalidate();
+                trianglifyView.invalidate();
```
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: Why is cell size seek bar just invalidating the view? it should call `generateAndInvalidate`

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 24]
```diff
@@ -23,6 +23,16 @@
...
 
+    /**
+     * flag for change in attributes
+     * if triangulation is null then value is -2
+     * if triangulation is unchanged then value is -1
+     * if change in grid width, grid height, variance, bleedX, bleedY, typeGrid or cell size then value is 1
+     * if change in palette or random coloring then value is 2
+     * if change in fillTriangle or drawStroke then value is 0
+     */
+    private int flagForChangeInRelatedParameters = -2;
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Use integers or enum instead:
```java
public static final int TRIANGULATION_NULL = 0;
public static final int TRIANGULATION_UNCHANGED = 1;
.
.
.
```

Comment (suyashmahar) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Also add a note before that to describe why this flag is required

File: README.md [hunk 25]
```diff
@@ -88,8 +88,7 @@ trianglifyView.setGridWidth(trianglifyView.getWidth())
     app:fillTriangle="true" />
 ```
 
-> TrianglifyView should be invalidated on change of any of the parameter for changes to take effect.To invalidate TrianglifyView call generateAndInvalidate method of TrianglifyView class.  
-**Note:** If any of the parameters is changed `TrianglifyView` regenerates every thing from scratch
+> TrianglifyView should be invalidated on change of any of the parameter for changes to take effect. To invalidate TrianglifyView call updateView method on the Trianglify View Instance.
```
Comment (suyashmahar) [inline README.md]: Method to invalidate view for any changes to take effect is generateAndInvalidate

Add behavioral description of following here or in a new point
* `invalidate`
* `generateAndInvalidate`

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java [hunk 26]
```diff
@@ -60,7 +60,7 @@ public void onStopTrackingTouch(SeekBar seekBar) {
             @Override
             public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                 trianglifyView.setCellSize(progress+100);
-                trianglifyView.generateAndInvalidate();
+                trianglifyView.updateView();
```
Comment (suyashmahar) [inline app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: Why is cell size seek bar just invalidating the view? it should call `generateAndInvalidate`

**Review by suyashmahar — COMMENTED** [review]
Fix these changes

File: app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java (hunk 26 above)
Comment (dakshitagrawal) [reply app/src/main/java/com/sdsmdg/kd/trianglifyexample/MainActivity.java]: it is calling the updateView() method. There it compares the flag, sees that it is 1, and hence calls generateAndInvalidate(). It can be called directly, but I have used updateView() so that there is uniformity in calling and one method to take care of all changes.

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java (hunk 24 above)
Comment (dakshitagrawal) [reply trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Yes, I will update the documentation.

File: README.md [hunk 27]
```diff
@@ -163,6 +160,14 @@ Palette customPalette = new Palette(int colors[]);
...
 > Array based constructor will throw `IllegalArgumentException` if size of array is not exactly 9.
 
+### 2.7 Updating the View
+
+`TrianglifyView` should be invalidated on change of any of the parameter for changes to take effect. To invalidate `TrianglifyView` call `updateView` method on the Trianglify View Instance. `updateView` can make the following two important calls:
+* `generateAndInvalidate`: this is called when the triangulation is to be generated from scratch, as in the case of change in `gridWidth`, `gridHeight`, `variance`, `bleedX`, `bleedY` or `cellSize`.
+* `generateNewColoredSoupAndInvalidate`: this is called when only the colorization of the triangulation is to be changed, ie `Palette` or `randomColoring' is changed.
+* `invalidateView`: this is called when the triangulation is to be rendered again. It calls the `onDraw` method of the view.
+
+
```
Comment (suyashmahar) [inline README.md]: `updateView` is a bit vague name, rename it to `smartUpdate` or something similar

Also update this part to explain exact difference and working, as: 

---------------------------------------------

### 2.7 Updating the View

Trianglify view can be update using two methods : 
#### Smart updating of view using `smartUpdate`
smartUpdate update view smartly, it checks for the changes in parameters from last update and decides accordingly what parts of view should be updated. More formal description is:
> Add complete description of updateView method, what changes when kind of
#### Complete regeneration using  `generateAndInvalidate`
 It regenerates everything from scratch (elaborate this point a bit more)

### (basic) Performance comparision of both method
.
.
.


Change headings and content according to your taste, but make content more descriptive and complete, so that someone who will use this does not get frustrated figuring out what it does

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java [hunk 28]
```diff
@@ -32,10 +32,23 @@
     private Triangulation triangulation;
     private TriangleGeneratorTask generatorTask;
 
+    /**
+     * flag that keeps track of whether just the color of the triangulation is to be changed or not.
+     */
+    private int justColor;
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/presenters/Presenter.java]: `justColor` is a vague term, rename it to something meaningful

File: trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java [hunk 29]
```diff
@@ -23,6 +23,17 @@
...
+    /**
+     * Flag for keeping track of changes in attributes of the view. Helpful in increasing
+     * performance by stopping unnecessary regeneration of triangulation. Look at updateView method for more.
+     * if triangulation is null then value is -2
+     * if triangulation is unchanged then value is -1
+     * if change in fillTriangle or drawStroke then value is 0
+     * if change in grid width, grid height, variance, bleedX, bleedY, typeGrid or cell size then value is 1
+     * if change in palette or random coloring then value is 2
+     */
+    private int flagForChangeInRelatedParameters = -2;
```
Comment (suyashmahar) [inline trianglify/src/main/java/com/sdsmdg/kd/trianglify/views/TrianglifyView.java]: Use enum for flags
something like:
```java
public enum ParameterChange {
    NULL_TRIANGULATION,
    UNCHANGED_TRIANGULATION,
.
.
.
}

and use them instead of numbers, numbers are confusing
```

File: README.md (hunk 27 above)
Comment (suyashmahar) [reply README.md]: In short be more descriptive when writing about API

**Review by suyashmahar — CHANGES_REQUESTED** [review]
Rest looks good

**Review by suyashmahar — APPROVED** [review]
Great work
